[WIP] Translate Variables  page until Uppercase constants
javascript-tutorial/az.javascript.info pull request #7
Opened 2020-02-15 08:25 UTC by GasimGasimzada

- [x] Overview
- [x] A Variable
- [x] Real-life Analogy
- [x] Variable naming
- [ ] Constants
- [ ] Name things right
- [ ] Summary
- [ ] Tasks

2020-07-21 19:38 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/1-hello-variables/solution.md
> +Aşağıdakı kodda olan hər sətir tapşıqıda olan hər maddəyə aiddir.
"tapşıqda" olan hər (there is a typo)

2020-07-21 19:43 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Nəzərə alın ki, biz `planet` adından istifadə edə bilərdik. Lakin, bu ad ilə hansı planetdən danışdığımız bilinməyəcəkdi. Daha məlumatlı adlar yazmaq yaxşıdır.
danışdığımız "bilinməyəcəkdir." (the word should end with r)
I think "aydın" better suits in the  sentence than "məlumatlı"

2020-07-21 19:44 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Əgər redaktorununzda avtomatik tamamlayıcı qurğu yoxdursa, [yeni redaktor əldə edin](/code-editors).
Please correct the typo

2020-07-21 19:45 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/2-declare-variables/task.md
> +1. Bizim planetimizin adında dəyişən yaradın. Bu dəyişəni necə adlandırardınız?
"Bizim planetimiz" is better

2020-07-21 19:46 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Normalda, biz əl ilə yazılan sabit dəyişənləri böyük hərf ilə yazırıq. Digər sözlə, dəyişənin dəyəri skriptin icrasından öncə bilindikdə və kodda birbaşa yazıldıqda biz bu dəyişəni böyük hərf ilə yaz
Digər sözlə, dəyişənin (there is no comma)

2020-07-21 19:46 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Bu kodda, `birthday` dəyişəninin bu formada olduğundan biz böyük hərfdən istifadə edə bilərik.
No comma

2020-07-21 19:49 UTC, azizaismayilova commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Lakin, `age` dəyişəni icra zamanı hesablanır. Bugün bizdə bir yaş, bir il sonra isə fərqli yaş olacaq. Bu dəyişən kod icrası zamanı dəyişmir amma bu dəyişən hesablanır deyə `birthday`-dən daha "az sa
Lakin, `age` dəyişəni (there is no comma)

2025-01-14 13:30 UTC, shahmal1yev commented
/done

2025-01-14 13:43 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Aşağıdakı ifadədə "message" adlı dəyişən yaradılır (digər sözlə, *bildirilir* ingiliscə, *declare*):
"Aşağıdaki ifadə "message" adlı bir dəyişən yaradır (başqa sözlə "elan edir")."

2025-01-14 13:47 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +İndi, biz `=` təyinat operatorundan istifadə edərək bu dəyişənə məlumat təyin edə bilərik:
"İndi biz mənimsətmə operatorundan (`=`) istifadə edərək bu dəyişənə bəzi məlumatlar yerləşdirə bilərik:"

2025-01-14 13:51 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +...vı ya "vergül-birinci" stilində də müəyyənləşdirirlər:
"vı ya" -> "və ya"

2025-01-14 14:43 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Bunun daha qısa olmasına baxmayaraq biz belə kod yazmağı tövsiyyə etmirik. Oxunaqlığı çoxaltmaq üçün hər dəyişən üçün ayrı sətir işlədin.
tövsiyyə -> tövsiyə

2025-01-14 14:45 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +`var` dəyişəni *az qala* `let` ilə eynidir. Bu açar sözü dəyişənin daha "köhnə" üsul ilə müəyyənləşdirir.
`var` açar sözü `let` açar sözü ilə *demək olar ki* eynidir. O da dəyişən elan edir, lakin bir qədər fərqli, "köhnə üsulla".

2025-01-14 14:47 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +"Dəyişən" konsepsiyasını yaxşı anlamaq üçün bunun, üzərində unikal adlı etiketi olan məlumatlar "qutusu" olduğunu fikirləşin.
Dəyişən anlayışını asanlıqla qavraya bilərik, əgər onu üzərində unikal ad yazılmış bir "etiket" olan məlumatlar üçün bir "qutu" kimi təsəvvür etsək.

2025-01-14 14:48 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Əlavə olaraq, biz iki dəyişən yaradıb birinin məlumatını o birisinə kopiyalaya bilərik.
Biz həmçinin iki dəyişən elan edib, birindən digərinə məlumatı kopyalaya bilərik.

2025-01-14 14:49 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Bu dillərdə, dəyər "qutuya" yerləşdirildikdən sonra orada ömürlük qalır. Fərqli məlumat saxlamaq istədikdə proqramlaşdırma dili bizə yeni qutu (dəyişənin yaradılması) yaratmağa məcbur edir. Biz köhnə
Belə dillərdə, dəyər "qutunun içinə" bir dəfə yerləşdirildikdən sonra, o, orada əbədi qalır. Əgər başqa bir şey saxlamağımız lazım olarsa, dil bizi yeni bir qutu (yeni dəyişən elan etməyi) yaratmağa məcbur edir. Köhnəsini yenidən istifadə edə bilmirik.

2025-01-14 14:52 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Aşağıdakı dəyişən adlar etibarlıdır:
Aşağıdakı dəyişən adlar etibarlıdır -> Aşağıdakı dəyişən etibarlıdır

2025-01-14 14:53 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Səhv məlumat adlarının nümunələri:
Yanlış dəyişən adlarına nümunələr:

2025-01-14 14:54 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +````smart header="Latın adlarını işlətmək olar, amma tövsiyyə edilmir"
- tövsiyyə -> tövsiyə
- işlətmək -> istifadə etmək

2025-01-14 14:58 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Texniki olaraq, burada heç bir xəta yoxdur. Lakin, beynəlxalq ənənəyə görə dəyişən adları İngiliscə yazılır. Kiçik skript yazsaq belə bu skriptin uzun həyatı ola bilər. Digər ölkələrdə olan proqramis
Texniki olaraq, burada heç bir səhv yoxdur, belə adlar uyğundur, lakin dəyişən adlarında ingilis dilindən istifadə etmək beynəlxalq bir ənənədir. Hətta kiçik bir skript yazsaq belə, onun uzun bir ömrü ola bilər. Başqa ölkələrdən olan insanlar bir gün onu oxumağa ehtiyac duya bilərlər.

2025-01-14 15:00 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Bunun pis praktika olduğundan bu sizə strikt rejimində xəta verəcək:
strikt rejimində -> sıx rejimdə

2025-01-14 15:00 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +`const` ilə yaranan dəyişənlər "sabit dəyişənlər" adlandırılır. Bu dəyişənləri yenidən təyin etmək mümkün deyil. Dəyişənin dəyərini dəyişmək istədikdə xəta baş verəcək:
yenidən təyin etmək -> yenidən elan etmək

2025-01-14 15:02 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Proqramçı dəyişənin heç vaxt dəyişməyəcəyindən əmin olduqda dəyişəni `const` ilə təyin edərək bu dəyişənin dəyişməyəcəyini siğortalayıb digər proqramçılara bildirə bilər.
Proqramçı bir dəyişənin heç vaxt dəyişməyəcəyinə əmin olduqda, bunu `const` ilə elan edə bilər ki, bunu təmin etsin və hər kəsə açıq şəkildə bildirsin.

2025-01-14 15:02 UTC, orkhan-huseyn commented on 1-js/02-first-steps/04-variables/article.md
> +`const` ilə yaranan dəyişənlər "sabit dəyişənlər" adlandırılır. Bu dəyişənləri yenidən təyin etmək mümkün deyil. Dəyişənin dəyərini dəyişmək istədikdə xəta baş verəcək:
@shahmal1yev elan etmək məncə, "declare" mənasına gəlir. `const` keywordü sadəcə assignmentin qarşısın alır. Burda assignment sözünə qarşılıq tapmaq lazımdır, misalçün mənimsətmək.

2025-01-14 15:03 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Praktikada, çətin yadda qalan dəyərlər skript icra olunmamışdan öncə sabit dəyişələr ilə ləqəbləndirilir.
İcra edilmədən əvvəl məlum olan və yadda saxlamaq çətin olan dəyərlər üçün sabit dəyişənlərdən təxəllüs kimi istifadə etmək geniş yayılmış bir praktikadır.

2025-01-14 15:03 UTC, orkhan-huseyn commented on 1-js/02-first-steps/04-variables/article.md
> +Bunun pis praktika olduğundan bu sizə strikt rejimində xəta verəcək:
sıx sözünü yəqin ki, türkcədəki "sıkı" sözündən götürmüsən. Bizdə də o mənaya gəlir?

2025-01-14 15:04 UTC, orkhan-huseyn commented on 1-js/02-first-steps/04-variables/article.md
> +Əlavə olaraq, biz iki dəyişən yaradıb birinin məlumatını o birisinə kopiyalaya bilərik.
məlumatı birindən digərinə köçürə bilərik

2025-01-14 15:04 UTC, orkhan-huseyn commented on 1-js/02-first-steps/04-variables/article.md
> +"Dəyişən" konsepsiyasını yaxşı anlamaq üçün bunun, üzərində unikal adlı etiketi olan məlumatlar "qutusu" olduğunu fikirləşin.
məncə, etiket və qutu sözlərində dırnağa ehtiyac yoxdur

2025-01-14 15:07 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Dəyişənləri adlandırmaq proqramlaşdırmada çox vacib və mürəkkəb bacarıqlardan biridir. Dəyişənin adına baxdıqda kodun yenibaşlayan və ya təcrübəli proqramçının yazdığını bilmək mümkündür.
Dəyişənin adına baxdıqda kodun yenibaşlayan və ya təcrübəli proqramçının yazdığını bilmək mümkündür. -> Dəyişən adlarına tez bir nəzər salmaqla, kodun başlanğıc səviyyəli bir proqramçı tərəfindən yoxsa təcrübəli bir proqramçı tərəfindən yazıldığını müəyyən etmək mümkündür.

2025-01-14 15:10 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Bəzi avara proqramçılar yeni dəyişən yaratmaq əvəzinə mövcud dəyişəni istifadə etməyi sevirlər.
Son olaraq, bəzi tənbəl proqramçılar, yeni dəyişənlər elan etmək əvəzinə, mövcud dəyişənləri yenidən istifadə etməyə meyllidirlər.

2025-01-14 15:11 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Nəticədə, bu dəyişənlər etiketi dəyişməyən, amma daxili dəyişən qutulara bənzəyirlər. Qutunun içində nəyin olduğunu heç kim bilmir. Bu səbəbdən, biz bu kodlara yaxından baxım yoxlamalıyıq.
baxım -> baxıb

2025-01-14 15:13 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Modern JavaScript minifikasiya edici qurğuları və brauzerlər kodu yaxşı optimallaşdırırlar. Bu səbəbdən, çox dəyişən yaratdıqda performans problemləri yaranmayacaq. Fərqli dəyərlər üçün fərqli dəyişə
Müasir JavaScript minifikasiya alətləri və brauzerlər kodu kifayət qədər yaxşı optimallaşdırır, buna görə performans problemləri yaratmayacaq. Fərqli dəyərlər üçün fərqli dəyişənlərdən istifadə etmək hətta mühərrikin kodunuzu daha yaxşı optimallaşdırmasına kömək edə bilər.

2025-01-14 15:15 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +- `const` -- `let` kimidir. Lakin, bununla yaranan dəyişənin dəyəri dəyişə bilməz.
- `let` — müasir dəyişən elanıdır.  
- `var` — köhnə üsulla dəyişən elanıdır. Adətən, ondan ümumiyyətlə istifadə etmirik, lakin <info:var> <info:var> bölməsində `let` və `var` arasında olan fərqlərdən danışacağıq.
- `const` — `let` kimidir, amma dəyişənin dəyəri dəyişdirilə bilməz.

2025-01-14 15:16 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Dəyişənləri, təyin olunan dəyəri yaxşı başa salan adlar ilə adlandırmağı tövsiyyə edirik.
Dəyişənlər elə adlandırılmalıdır ki, onların içində nə olduğunu asanlıqla anlaya bilək.

2025-01-14 15:18 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +"Dəyişən" konsepsiyasını yaxşı anlamaq üçün bunun, üzərində unikal adlı etiketi olan məlumatlar "qutusu" olduğunu fikirləşin.
dırnaqların istifadə olunması onun məcazi anlamda olmasına vurğu edir, bu sözlər təbii ki, dilimizdə mövcuddu

2025-01-14 15:22 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/article.md
> +Bunun pis praktika olduğundan bu sizə strikt rejimində xəta verəcək:
xeyr, bunu müəllimim istifadə edirdi. Oradan xatırlayıram. Mənə görə anlamlıdı, yenə də üzərində düşünülüb daha uyğun bir ad tapılarsa, lüğətə (#23) əlavə ediləcəyi təqdirdə çox yaxşı olar

2025-01-14 15:29 UTC, shahmal1yev requested changes
işlətmək      -> istifadə etmək
tövsiyyə      -> tövsiyə
strict mode -> sıx rejim

2025-01-15 06:43 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/1-hello-variables/solution.md
> +let admin, name; // eyni zamanda iki dəyişən yaratmaq mümkündür
eyni zamanda iki dəyişən elan etmək olar

2025-01-15 06:46 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/1-hello-variables/task.md
> +4. `admin` dəyişəninin dəyərini `alert` ilə göstərin ("Orxan" göstərməlidir).
1. İki dəyişən elan edin: `admin` və `name`.  
2. `name` dəyişəninə `"Orxan"` dəyərini təyin edin.  
3. `name` dəyişənindən `admin` dəyişəninə dəyəri kopyalayın.  
4. `admin` dəyişəninin dəyərini `alert` istifadə edərək göstərin (nəticə "Orxan" olmalıdır).

2025-01-15 06:46 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +## Bizim planetimizin dəyişəni
## Bizim planet üçün dəyişən

2025-01-15 06:47 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Bu asandır:
Bu sadədir:

2025-01-15 06:48 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Nəzərə alın ki, biz `planet` adından istifadə edə bilərdik. Lakin, bu ad ilə hansı planetdən danışdığımız bilinməyəcəkdir. Daha aydın adlar yazmaq yaxşıdır.
Qeyd edək ki, daha qısa `planet` adı istifadə edə bilərdik, amma onun hansı planetə aid olduğu aydın olmaya bilər. Daha izahlı olmaq yaxşıdır. Ən azı dəyişən çox uzun olmadığı müddətcə.

2025-01-15 06:52 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Biz bu dəyişənin həmişə cari istifadəçi haqqında olduğunu bilsəydik bu dəyişəni `userName` adlandıra bilərdik.
Yenə də, əgər istifadəçinin cari olduğunu dəqiq bilsək, bunu `userName` kimi qısalda bilərik.

2025-01-15 07:27 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/2-declare-variables/solution.md
> +Modern redaktorlarda olan avtomatik tamamlayıcı qurğular ilə uzun adları yazmaq asanlaşır. Üç sözdən ibarət ad normaldır.
Müasir redaktorlar və avtomatik tamamlanma xüsusiyyəti uzun dəyişən adlarını yazmağı asanlaşdırır. Onlardan qənaət etməyin. Üç sözlük bir ad tamamilə qəbul ediləndir.

2025-01-15 07:29 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Normalda, biz əl ilə yazılan sabit dəyişənləri böyük hərf ilə yazırıq. Digər sözlə dəyişənin dəyəri skriptin icrasından öncə bilindikdə və kodda birbaşa yazıldıqda biz bu dəyişəni böyük hərf ilə yazı
hərf ilə -> hərflərlə

2025-01-15 07:30 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Bu kodda `birthday` dəyişəninin bu formada olduğundan biz böyük hərfdən istifadə edə bilərik.
Bu kodda `birthday` məhz belədir. Ona görə də onun üçün böyük hərflərdən istifadə edə bilərik.

2025-01-15 07:32 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
> +Lakin `age` dəyişəni icra zamanı hesablanır. Bugün bizdə bir yaş, bir il sonra isə fərqli yaş olacaq. Bu dəyişən kod icrası zamanı dəyişmir amma bu dəyişən hesablanır deyə `birthday`-dən daha "az sab
Lakin `age` dəyişəni icra zamanı hesablanır. Bu gün bizdə fərqli bir yaş, bir il sonra isə fərqli bir yaş olacaq. Bu dəyişən kod icrası zamanı dəyişmir amma bu dəyişən hesablanır deyə `birthday`-dən "daha az sabitdir". Bu səbəbdən, bu dəyişənin adı böyük hərflərlə yazılmamalıdır.

2025-01-15 07:33 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
> +# Böyük hərf ilə const?
hərflərlə

2025-01-15 07:36 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
> +Burada `birthday` adlı sabit zaman dəyişəni və `birthday`-dən hesablanan `age` sabit dəyişəni var (hesablama funksiyasının vacib olmadığından bu kodun tətbiq detalı göstərilməyib).
Burada `birthday` olaraq adlandırılmış, bir tarix dəyəri saxlayan konstantımız var. `age` həmin `birthday` və müəyyən bir kodun köməyi ilə hesablanır (qısa olsun deyə və təfərrüatlar burada əhəmiyyətli olmadığı üçün bu kod təmin edilməyib)

2025-01-15 07:37 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
> +`birthday` üçün böyük hərf işlətmək yaxşı fikirdir? Bəs `age` üçün? Bəs hər ikisi üçün?
`birthday` üçün böyük hərflərdən istifadə etmək yaxşı fikirdir?

2025-01-15 07:37 UTC, shahmal1yev commented on 1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
> +const BIRTHDAY = '18.04.1982'; // böyük hərf ilə yazaq?
hərflərlə

2025-01-15 08:00 UTC, shahmal1yev approved these changes

2025-01-15 08:42 UTC, merged